# This file is part of REANA.
# Copyright (C) 2017, 2018, 2019 CERN.
#
# REANA is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

notifications:
  email: false

sudo: true

language: python

cache:
  - pip

matrix:
  fast_finish: true
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8

before_install:
  - travis_retry pip install --upgrade pip setuptools py
  - travis_retry pip install twine wheel coveralls

install:
  - travis_retry pip install -e .[all]
  - mkdir bin
  - wget https://get.helm.sh/helm-v3.2.1-linux-amd64.tar.gz -O helm.tar.gz
  - tar -xzf helm.tar.gz -C $PWD/bin --strip-components=1
  - chmod +x $PWD/bin/helm
  - export PATH=$PWD/bin:$PATH

script:
  - ./run-tests.sh

after_success:
  - coveralls
