apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reana.prefix" . }}-db-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  user: {{ .Values.secrets.database.user | default "reana" | b64enc }}
  password: {{ .Values.secrets.database.password | default "reana" | b64enc }}
