apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "reana.prefix" . }}-ingress
  namespace: {{ .Release.Namespace }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls.self_signed_cert }}
  tls:
    - secretName: {{ include "reana.prefix" . }}-tls-secret
  {{- end }}
  rules:
    - http:
        paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: {{ include "reana.prefix" . }}-server
              port:
                number: 80
        - path: /oauth
          pathType: Prefix
          backend:
            service:
              name: {{ include "reana.prefix" . }}-server
              port:
                number: 80
        {{- if .Values.components.reana_ui.enabled }}
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "reana.prefix" . }}-ui
              port:
                number: 80
        {{- end }}
      {{- if .Values.reana_hostname }}
      host: {{ .Values.reana_hostname }}
      {{- end }}
