{{- if .Values.ingress.enabled }}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "reana.prefix" . }}-ingress
  namespace: {{ .Release.Namespace }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - http:
        paths:
        - path: /api
          backend:
            serviceName: {{ include "reana.prefix" . }}-server
            servicePort: 80
        - path: /oauth
          backend:
            serviceName: {{ include "reana.prefix" . }}-server
            servicePort: 80
        {{- if .Values.components.reana_ui.enabled }}
        - path: /
          backend:
            serviceName: {{ include "reana.prefix" . }}-ui
            servicePort: 80
        {{- end }}
      {{- if .Values.reana_url }}
      host: {{ .Values.reana_url }}
      {{- end }}
{{- end }}
