{{- if .Values.pgbouncer.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reana.prefix" . }}-pgbouncer-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  userlist: {{ printf "%s %s" (.Values.secrets.database.user | default "reana" | quote) (.Values.secrets.database.password | default "reana" | quote) | b64enc}}
{{- end }}
