---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reana.prefix" . }}-server
  namespace: {{ .Release.Namespace }}
spec:
  type: "NodePort"
  ports:
  - port: 80
    targetPort: 5000
    name: "http"
    protocol: TCP
  selector:
    app: {{ include "reana.prefix" . }}-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reana.prefix" . }}-server
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "reana.prefix" . }}-server
  template:
    metadata:
      labels:
        app: {{ include "reana.prefix" . }}-server
    spec:
      serviceAccountName: {{ include "reana.prefixed_infrastructure_svaccount_name" . }}
      containers:
      - name: rest-api
        image: {{ .Values.components.reana_server.image }}
        imagePullPolicy: {{ .Values.components.reana_server.imagePullPolicy }}
        ports:
        - containerPort: 5000
          name: http
        {{- if .Values.debug.enabled }}
        command: ["/bin/sh", "-c"]
        args: ["invenio run -h 0.0.0.0 -p 5000"]
        tty: true
        stdin: true
        {{- else }}
        command: ["/bin/sh", "-c"]
        args: ["uwsgi --ini /var/reana/uwsgi/uwsgi.ini"]
        {{- end }}
        volumeMounts:
          {{- if .Values.debug.enabled }}
          - mountPath: /code/
            name: reana-code
          {{- end }}
          - mountPath: {{ .Values.shared_storage.shared_volume_mount_path }}
            name: reana-shared-volume
          {{- range $workspace_paths := .Values.workspaces.paths }}
          {{- if not (eq $workspace_paths "/var/reana")}}
          - name: {{ $workspace_paths | quote |replace "/" "" }}
            mountPath: {{ $workspace_paths }}
            mountPropagation: HostToContainer
          {{- end }}
          {{- end }}
          - name: uwsgi-config
            mountPath: '/var/reana/uwsgi'
          - name: reana-config
            mountPath: '/var/reana/config'
        env:
          - name: REANA_COMPONENT_PREFIX
            value: {{ include "reana.prefix" . }}
          - name: REANA_INFRASTRUCTURE_KUBERNETES_NAMESPACE
            value: {{ .Release.Namespace }}
          - name: REANA_RUNTIME_KUBERNETES_NAMESPACE
            value: {{ .Values.namespace_runtime | default .Release.Namespace }}
          - name: REANA_DEFAULT_QUOTA_CPU_LIMIT
            value: {{ .Values.quota.default_cpu_limit | default 0 | quote }}
          - name: REANA_DEFAULT_QUOTA_DISK_LIMIT
            value: {{ .Values.quota.default_disk_limit | default 0 | quote }}
          - name: REANA_KUBERNETES_JOBS_MEMORY_LIMIT
            value: {{ .Values.kubernetes_jobs_memory_limit | default "4Gi" }}
          - name: WORKSPACE_PATHS
            value: {{ join "," .Values.workspaces.paths }}
          {{- if not (eq (index .Values.workspaces.paths 0) "/var/reana")}}
          - name: DEFAULT_WORKSPACE_PATH
            value: {{ index .Values.workspaces.paths 0 }}
          {{- else if ( gt (len .Values.workspaces.paths) 1)}}
          - name: DEFAULT_WORKSPACE_PATH
            value: {{ index .Values.workspaces.paths 1 }}
          {{- end }}
          {{- range $key, $value := .Values.db_env_config }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          {{- range $key, $value := .Values.components.reana_server.environment }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          {{- if .Values.reana_hostname }}
          - name: REANA_HOSTNAME
            value: {{ .Values.reana_hostname }}
          {{- end }}
          - name: CERN_CONSUMER_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "reana.prefix" . }}-cern-sso-secrets
                key: CERN_CONSUMER_KEY
          - name: CERN_CONSUMER_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ include "reana.prefix" . }}-cern-sso-secrets
                key: CERN_CONSUMER_SECRET
          - name: REANA_GITLAB_OAUTH_APP_ID
            valueFrom:
              secretKeyRef:
                name: {{ include "reana.prefix" . }}-cern-gitlab-secrets
                key: REANA_GITLAB_OAUTH_APP_ID
          - name: REANA_GITLAB_OAUTH_APP_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ include "reana.prefix" . }}-cern-gitlab-secrets
                key: REANA_GITLAB_OAUTH_APP_SECRET
          - name: REANA_GITLAB_HOST
            valueFrom:
              secretKeyRef:
                name: {{ include "reana.prefix" . }}-cern-gitlab-secrets
                key: REANA_GITLAB_HOST
          - name: REANA_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "reana.prefix" . }}-secrets
                key: REANA_SECRET_KEY
          {{- if .Values.debug.enabled }}
          # Disable CORS in development environment, for example
          # to connect from an external React application.
          - name: INVENIO_CORS_SEND_WILDCARD
            value: "False"
          - name: INVENIO_CORS_SUPPORTS_CREDENTIALS
            value: "True"
          - name: WDB_SOCKET_SERVER
            value: "{{ include "reana.prefix" . }}-wdb"
          - name: WDB_NO_BROWSER_AUTO_OPEN
            value: "True"
          - name: FLASK_ENV
            value:  "development"
          # Hack to not verify SSL connections https://stackoverflow.com/questions/48391750/disable-python-requests-ssl-validation-for-an-imported-module
          - name: CURL_CA_BUNDLE
            value: ""
          - name: GIT_SSL_NO_VERIFY
            value: "true"
          {{- else }}
          - name: REANA_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ include "reana.prefix" . }}-db-secrets
                key: user
          - name: REANA_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "reana.prefix" . }}-db-secrets
                key: password
          {{- end }}
          {{- if .Values.notifications.enabled }}
          - name: REANA_EMAIL_SENDER
            value: {{ .Values.notifications.email_config.sender }}
          - name: REANA_EMAIL_SMTP_SERVER
            value: {{ .Values.notifications.email_config.smtp_server | default (printf "%s-mail" (include "reana.prefix" .)) }}
          - name: REANA_EMAIL_SMTP_PORT
            value: "{{ .Values.notifications.email_config.smtp_port | default "30025" }}"
          {{- if not .Values.debug.enabled }}
          - name: REANA_EMAIL_LOGIN
            valueFrom:
              secretKeyRef:
                name: {{ include "reana.prefix" . }}-mail-notification-sender-password
                key: REANA_EMAIL_LOGIN
          - name: REANA_EMAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "reana.prefix" . }}-mail-notification-sender-password
                key: REANA_EMAIL_PASSWORD
          {{- end }}
          {{- end }}
      - name: scheduler
        image: {{ .Values.components.reana_server.image }}
        imagePullPolicy: {{ .Values.components.reana_server.imagePullPolicy }}
        command: ["flask", "start-scheduler"]
        volumeMounts:
          {{- if .Values.debug.enabled }}
          - mountPath: /code/
            name: reana-code
          {{- end }}
          - mountPath: {{ .Values.shared_storage.shared_volume_mount_path }}
            name: reana-shared-volume
        env:
        - name: REANA_COMPONENT_PREFIX
          value: {{ include "reana.prefix" . }}
        - name: REANA_INFRASTRUCTURE_KUBERNETES_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: REANA_RUNTIME_KUBERNETES_NAMESPACE
          value: {{ .Values.namespace_runtime | default .Release.Namespace }}
        {{- range $key, $value := .Values.db_env_config }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- range $key, $value := .Values.components.reana_server.environment }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- if .Values.debug.enabled }}
        # Disable CORS in development environment, for example
        # to connect from an external React application.
        - name: INVENIO_CORS_SEND_WILDCARD
          value: "False"
        - name: INVENIO_CORS_SUPPORTS_CREDENTIALS
          value: "True"
        - name: WDB_SOCKET_SERVER
          value: "{{ include "reana.prefix" . }}-wdb"
        - name: WDB_NO_BROWSER_AUTO_OPEN
          value: "True"
        - name: FLASK_ENV
          value:  "development"
        # Hack to not verify SSL connections https://stackoverflow.com/questions/48391750/disable-python-requests-ssl-validation-for-an-imported-module
        - name: CURL_CA_BUNDLE
          value: ""
        - name: GIT_SSL_NO_VERIFY
          value: "true"
        {{- else }}
        - name: REANA_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ include "reana.prefix" . }}-db-secrets
              key: user
        - name: REANA_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "reana.prefix" . }}-db-secrets
              key: password
        {{- end }}
      volumes:
      - name: reana-shared-volume
        {{- if not (eq .Values.shared_storage.backend "hostpath") }}
        persistentVolumeClaim:
          claimName: {{ include "reana.prefix" . }}-shared-persistent-volume
          readOnly: false
        {{- else }}
        hostPath:
          path:  {{ .Values.shared_storage.hostpath.root_path }}
        {{- end }}
      {{- if .Values.debug.enabled }}
      - name: reana-code
        hostPath:
          path: /code/reana-server
      {{- end }}
      - name: uwsgi-config
        configMap:
          defaultMode: 420
          name: uwsgi-config
      - name: reana-config
        configMap:
          defaultMode: 420
          name: reana-config
      {{- if .Values.node_label_infrastructure }}
      {{- $full_label := split "=" .Values.node_label_infrastructure }}
      nodeSelector:
        {{ $full_label._0 }}: {{ $full_label._1 }}
      {{- end }}
      {{- range $workspace_paths := .Values.workspaces.paths }}
      {{- if not (eq $workspace_paths "/var/reana")}}
      - name: {{ $workspace_paths | quote |replace "/" "" }}
        hostPath:
          path: {{ $workspace_paths }}
      {{- end }}
      {{- end }}
