---
apiVersion: v1
kind: Service
metadata:
  name: reana-message-broker
spec:
  ports:
   - port: 5672
     targetPort: 5672
     name: "tcp"
     protocol: TCP
   - port: 15672
     targetPort: 15672
     name: "management"
     protocol: TCP
  selector:
    app: reana-message-broker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reana-message-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reana-message-broker
  template:
    metadata:
      labels:
        app: reana-message-broker
    spec:
      containers:
      - name: message-broker
        image: {{ .Values.components.reana_message_broker.image }}
        imagePullPolicy: {{ .Values.components.reana_message_broker.imagePullPolicy }}
        ports:
        - containerPort: 5672
          name: tcp
        - containerPort: 15672
          name: management
