---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reana.prefix" . }}-cache
spec:
  type: NodePort
  selector:
    app: {{ include "reana.prefix" . }}-cache
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reana.prefix" . }}-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "reana.prefix" . }}-cache
  template:
    metadata:
      labels:
        app: {{ include "reana.prefix" . }}-cache
    spec:
      containers:
      - name: cache
        image: redis:5.0.5
        ports:
        - containerPort: 6379
