---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: reana-deployment-manager
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["nodes", "nodes/status", "pods", "pods/log", "secrets", "persistentvolumeclaims", "configmaps"]
  verbs: ["get", "list", "create", "update", "watch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["*"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Interactive web notebooks permissions
- apiGroups: ["", "extensions", "apps", "networking.k8s.io"]
  resources: ["deployments", "services", "ingresses"]
  verbs: ["get", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: reana-manage-deployments
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: reana-deployment-manager
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: default
