---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reana.prefix" . }}-db-secrets
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  user: {{ .Values.secrets.database.user | default "reana" | b64enc }}
  password: {{ .Values.secrets.database.password | default "reana" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reana.prefix" . }}-cern-sso-secrets
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  CERN_CONSUMER_KEY: {{ .Values.secrets.cern.sso.CERN_CONSUMER_KEY | default "cern_consumer_key" | b64enc }}
  CERN_CONSUMER_SECRET: {{ .Values.secrets.cern.sso.CERN_CONSUMER_SECRET | default "cern_consumer_secret" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reana.prefix" . }}-cern-gitlab-secrets
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  REANA_GITLAB_OAUTH_APP_ID: {{ .Values.secrets.gitlab.REANA_GITLAB_OAUTH_APP_ID | default "reana_gitlab_oauth_app_id" | b64enc }}
  REANA_GITLAB_OAUTH_APP_SECRET: {{ .Values.secrets.gitlab.REANA_GITLAB_OAUTH_APP_SECRET | default "reana_gitlab_oauth_app_secret" | b64enc }}
  REANA_GITLAB_HOST: {{ .Values.secrets.gitlab.REANA_GITLAB_HOST | default "gitlab.cern.ch" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reana.prefix" . }}-secrets
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  REANA_SECRET_KEY: {{ .Values.secrets.reana.REANA_SECRET_KEY | default "secret_key" | b64enc }}
{{- if .Values.notifications.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reana.prefix" . }}-mail-notification-sender-password
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  REANA_EMAIL_LOGIN: {{ .Values.notifications.email_config.login | default "team@reana.io" | b64enc }}
  REANA_EMAIL_PASSWORD: {{ .Values.notifications.email_config.password | default "CHANGEME" | b64enc }}
{{- end }}
