---
apiVersion: v1
kind: Secret
metadata:
  name: reana-db-secrets
type: Opaque
data:
  user: {{ .Values.secrets.database.user | default "reana" | b64enc }}
  password: {{ .Values.secrets.database.password | default "reana" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
    name: reana-cern-sso-secrets
type: Opaque
data:
  CERN_CONSUMER_KEY: {{ .Values.secrets.cern.sso.CERN_CONSUMER_KEY | default "cern_consumer_key" | b64enc }}
  CERN_CONSUMER_SECRET: {{ .Values.secrets.cern.sso.CERN_CONSUMER_SECRET | default "cern_consumer_secret" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
    name: reana-cern-gitlab-secrets
type: Opaque
data:
  REANA_GITLAB_OAUTH_APP_ID: {{ .Values.secrets.gitlab.REANA_GITLAB_OAUTH_APP_ID | default "reana_gitlab_oauth_app_id" | b64enc }}
  REANA_GITLAB_OAUTH_APP_SECRET: {{ .Values.secrets.gitlab.REANA_GITLAB_OAUTH_APP_SECRET | default "reana_gitlab_oauth_app_secret" | b64enc }}
  REANA_GITLAB_HOST: {{ .Values.secrets.gitlab.REANA_GITLAB_HOST | default "gitlab.cern.ch" | b64enc }}
