# Default values for reana.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# reana_url: reana.cern.ch
# `reana_url` should be set for third party integrations to work and for
# production deployments to be secure.

debug:
  enabled: false
eos:
  enabled: false

shared_storage:
  backend: hostpath # hostpath | cephfs | nfs
  volume_size: 200
  access_modes: ReadWriteMany
  shared_volume_mount_path: "/var/reana"
  hostpath:
    root_path: "/var/reana"
  cephfs:
    provisioner: manila-provisioner
    type: "Geneva CephFS Testing"
    availability_zone: nova
    os_necret_name: os-trustee
    os_necret_namespace: kube-system
    cephfs_os_share_id: <cephfs-share-id>
    cephfs_os_share_access_id: <cephfs-share-access-id>

secrets:
  database: {}
  gitlab: {}
  cern:
    sso: {}
  reana: {}

# External database service configuration
db_env_config:
  REANA_DB_NAME: "reana"
  REANA_DB_PORT: "5432"
  # There are two more environment variables that should be set in order
  # to connect to a database:
  # REANA_DB_USERNAME: containing the database user name.
  # REANA_DB_PASSWORD: containing the password for the user previously set.
  # Both environment variables should be set inside a Kubernetes secret:
  # `[release-name]-db-secrets`

# REANA components configuration
components:
  reana_ui:
    enabled: false
  reana_db:
    enabled: true
  reana_server:
    imagePullPolicy: IfNotPresent
    image: reanahub/reana-server:0.6.0-53-g7984143
    environment:
      REANA_MAX_CONCURRENT_BATCH_WORKFLOWS: 30
    uwsgi:
      processes: 6
      threads: 4
  reana_workflow_controller:
    imagePullPolicy: IfNotPresent
    image: reanahub/reana-workflow-controller:0.6.0-36-gb702986
    environment:
      SHARED_VOLUME_PATH: /var/reana
  reana_workflow_engine_cwl:
    image: reanahub/reana-workflow-engine-cwl:0.6.0-9-gcda4d46
  reana_workflow_engine_yadage:
    image: reanahub/reana-workflow-engine-yadage:0.6.0-14-g7f9773c
  reana_workflow_engine_serial:
    image: reanahub/reana-workflow-engine-serial:0.6.0-13-gef2eb4c
  reana_job_controller:
    image: reanahub/reana-job-controller:0.6.0-31-g35c4fc8
  reana_message_broker:
    imagePullPolicy: IfNotPresent
    image: reanahub/reana-message-broker:0.6.0-1-gac35315
  reana_ui:
    imagePullPolicy: IfNotPresent
    image: reanahub/reana-ui:0.6.0-59-g9dacae5

notifications:
  enabled: false
  email_config: {}
  system_status: "0 0 * * *"

# Accessing the cluster from outside world
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.entryPoints: "http,https"
    ingress.kubernetes.io/ssl-redirect: "true"

# Permissions
serviceAccount:
  create: true
  name: reana
  namespace: default

# Traefik's chart values.yaml
traefik:
  enabled: true
  rbac:
    enabled: true
  dashboard:
    enabled: true
  kubernetes:
    namespaces:
      - default
      - kube-system
  serviceType: NodePort
  service:
    nodePorts:
      http: 30080
      https: 30443
  ssl:
    enabled: true
    generateTLS: true
